config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "home#index"
  resources :todos
  get '/users', to: "users#index", as: "users_index"
  get '/users/:id', to: "users#show", as: "users_show"

end

app/models/list.rb
class List < ActiveRecord::Base
  has_many :todos
  belongs_to :user
end

app/models/todo.rb
class ToDo <ActiveRecord::Base
  belongs_to :user
  belongs_to :list
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :todos
  has_many :lists
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @users = User.all
    redirect_to users_index_path
  end

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  def index

  end

  def show

  end

  def update

  end

  def destroy

  end

  def create

  end

end

app/controllers/todos_controller.rb
class ToDosController < ApplicationController

  def index
    @todos = ToDo.all
  end

  def show
    @todo = ToDo.find(params[:id])
  end

  def create
    @todo = Todo.create(todo_params)
  end

  def update
    @todo = ToDo.find(params[:id])
    @todo.update(todo_params)
  end

  def destroy
    @todo = ToDo.find(params[:id])
    @todo.destroy!
  end

  private

    def todo_params
      params.require(:todo).permit(:user_id, :todo_id, :taskname, :body, :finished)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController


  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TodoMvc</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>

<%= yield %>

</body>
</html>

app/views/users/index.html.erb
<h1> Welcome to ToDo's Homepage </h1>

  <%= link_to 'Profile Page', users_show_path(current_user) %>
  <br>
  ------------------------------------------------
  <br>
  <br>
  <% @users.each do |u| %>
    <%= u.email %>


  <%end%>

app/views/users/show.html.erb
<h1> Welcome to Your Profile Page </h1>
<br>
  <%= link_to 'Back to User Index', users_index_path %> |  <%= link_to 'ToDo List', todos_path %>
<br>
---------------------------
<br>
<br>
<%= @user.email %>